Missed viral load pmtctrri
palladiumkenya/dwh-etl pull request #169
Opened 2023-04-19 10:46 UTC by Marymary-dev

2023-04-24 11:37 UTC, nobert-mumo requested changes

2023-04-24 11:37 UTC, nobert-mumo commented on Scripts/ODS/utils/pmtct_rri_models/MissedViralLoad.sql
> +
@Marymary-dev  looks like we missed some age groups here; These 2 give different results:
`    select 
        count(*) as calhiv 
    from REPORTING.dbo.Linelist_FACTART
    where AgeGroup in ('1 to 4','10 to 14','Under 1','15 to 19') and ARTOutcome='V'
`
VS
   ` select 
        count(*) as calhiv 
    from REPORTING.dbo.Linelist_FACTART
    where  age <= 19 and IsTXCurr = 1`

2023-04-24 16:49 UTC, Marymary-dev commented on Scripts/ODS/utils/pmtct_rri_models/MissedViralLoad.sql
> +
Change effected and where clause changed to 
where  age <= 19 and IsTXCurr = 1

2023-04-27 08:11 UTC, nobert-mumo approved these changes

2023-05-04 18:15 UTC, merged