Feature/Aggregate-tables-able-to-plot-time-series-data- Part 1
palladiumkenya/dwh-etl pull request #222
Opened 2023-08-03 06:14 UTC by nobert-mumo

We want users to be able to group data by time periods e.g month, year,quarter, etc on the aggregate table. This PR introduced a column `AsOfDate` which is the end of month for each month. This will enable time series analysis on the aggregates table

Jira ticket: https://thepalladiumgroup.atlassian.net/browse/KHP3-3606

2023-08-03 06:26 UTC, Marymary-dev approved these changes

2023-08-07 06:35 UTC, cbrianbet requested changes

2023-08-07 06:35 UTC, cbrianbet commented on Scripts/REPORTING/load_aggregate_hts_months_last_test.sql
Hi @nobert-mumo I see you are changing the table for this dataset from AggregateHTSMonthsLastTest to AggregateHTSPNSSexualPartner

2023-08-07 08:43 UTC, nobert-mumo commented on Scripts/REPORTING/load_aggregate_hts_months_last_test.sql
@cbrianbet good catch! oops. will correct that.

2023-08-07 09:12 UTC, nobert-mumo commented on Scripts/REPORTING/load_aggregate_hts_months_last_test.sql
@cbrianbet made the correction.

2023-08-07 10:10 UTC, cbrianbet commented
👍

2023-08-07 12:36 UTC, merged