Pregnant & breastfeeding mothers addition
palladiumkenya/dwh-etl pull request #226
Opened 2023-08-22 11:38 UTC by Marymary-dev

2023-08-23 09:57 UTC, nobert-mumo commented on Scripts/NDWH/C&T FACT TABLES/load_FactViralLoad.sql
> +        /*Pregnant & Breastfeeding mothers  who  have a valid VL that is within the last 6 months from reporting period**/
@Marymary-dev

2023-08-23 10:02 UTC, nobert-mumo requested changes

2023-08-23 10:02 UTC, nobert-mumo commented on Scripts/NDWH/C&T FACT TABLES/load_FactViralLoad.sql
> +            inner join NDWH.dbo.FactLatestObs as obs on obs.PatientKey=pat.PatientKey
@Marymary-dev joining here on Dims and Facts might be a problem because of the interdependency coz Facts & Dims would be loaded together? Maybe the best approach would be to get the info from intermediates?

2023-08-23 10:04 UTC, nobert-mumo commented on Scripts/NDWH/C&T FACT TABLES/load_FactViralLoad.sql
> +        /*Pregnant & Breastfeeding mothers  who  have a valid VL that is within the last 6 months from reporting period**/
@Marymary-dev we should also add the indicator to the reporting layer, which would be the best dataset to add this ? `LineListViralLoad` ?

2023-08-23 10:05 UTC, nobert-mumo commented
@Marymary-dev  for the DATIM unsuppressed indicator you wanted to handle it in a different PR?

2023-08-23 18:43 UTC, Marymary-dev commented on Scripts/NDWH/C&T FACT TABLES/load_FactViralLoad.sql
> +            inner join NDWH.dbo.FactLatestObs as obs on obs.PatientKey=pat.PatientKey
This has been refactored to join to intermediate_LatestObs instead of FACT_LatestObs

2023-08-23 20:02 UTC, Marymary-dev commented on Scripts/NDWH/C&T FACT TABLES/load_FactViralLoad.sql
> +        /*Pregnant & Breastfeeding mothers  who  have a valid VL that is within the last 6 months from reporting period**/
Added PBFValidVL in the linelist viral load

2023-08-24 06:33 UTC, nobert-mumo commented on Scripts/NDWH/C&T FACT TABLES/load_FactViralLoad.sql
> +        union
@Marymary-dev  I was thinking maybe we can get this from the union into its own independent CTE e.g. 

`PBFValidVL as ( .... )`

I think it would be clearer there.

2023-08-24 12:23 UTC, nobert-mumo approved these changes
LGTM @Marymary-dev

2023-08-24 12:34 UTC, merged