Adding numer of patients booked in appointment status
palladiumkenya/dwh-etl pull request #231
Opened 2023-08-25 08:24 UTC by Marymary-dev

2023-08-30 12:43 UTC, Marymary-dev commented on Scripts/REPORTING/load_aggregate_Appointments.sql
> +  left join Bookings on Bookings.FacilityKey = Summary.FacilityKey
Done

2023-08-31 16:09 UTC, Marymary-dev commented on Scripts/REPORTING/load_aggregate_Appointments.sql
> +Select
Done

2023-09-01 06:55 UTC, nobert-mumo requested changes

2023-09-01 06:55 UTC, nobert-mumo commented on Scripts/REPORTING/load_aggregate_Appointments.sql
> +  Summary.AsOfDateKey,
@Marymary-dev just a small one we can have this as a date to enable plotting time series on the BI tools.

2023-09-01 18:22 UTC, Marymary-dev commented on Scripts/REPORTING/load_aggregate_Appointments.sql
> +  Summary.AsOfDateKey,
Done

2023-09-02 08:14 UTC, nobert-mumo approved these changes

2023-09-02 08:17 UTC, nobert-mumo commented
@Marymary-dev LGTM, didn't check the actual data, this looks similar to the one on HTS Uptake + TX New model that had a bug. Hopefully, it's taken care of.

2023-10-23 06:28 UTC, nobert-mumo commented
@Marymary-dev, pushed the changes, you can have a look.

2023-10-23 06:44 UTC, merged