Adding aggregate_Ushauri_sms_reminders
palladiumkenya/dwh-etl pull request #352
Opened 2024-01-19 18:19 UTC by Marymary-dev

2024-01-21 19:04 UTC, nobert-mumo requested changes

2024-01-21 19:04 UTC, nobert-mumo commented on Scripts/REPORTING/load_aggregate_Ushauri_sms_reminders.sql
> +         COALESCE( Try_CONVERT(date, FourWeekSMSSendDate), Try_CONVERT(date, ThreeWeekSMSSendDate), Try_CONVERT(date, TwoWeekSMSSendDate), Try_CONVERT(date, OneWeekSMSSendDate), Try_CONVERT (date, On
@Marymary-dev for readability maybe we can have each column in a newline.

2024-01-21 19:04 UTC, nobert-mumo commented on Scripts/REPORTING/load_aggregate_Ushauri_sms_reminders.sql
> +IF OBJECT_ID(N'[Reporting].[Dbo].[aggregateUshauriSMSReminders]', N'U') IS NOT NULL DROP TABLE [Reporting].[Dbo].[aggregateUshauriSMSReminders];
@Marymary-dev nitpik: Maybe we can rename to be in CamelCase e.g. `AggregateUshauriSMSReminders`

consider newline begining `DROP ...` :)

2024-01-23 14:04 UTC, nobert-mumo commented on Scripts/REPORTING/load_aggregate_Ushauri_sms_reminders.sql
> +IF Object_id(N'[Reporting].[Dbo].[AggregateUshauriSMSReminders]', N'U') IS NOT NULL
@Marymary-dev do we want to only show disaggregation by AsOfDate or also the other standard dimensions e.g Facility, AgeGroup, Partner, Agency etc ?

2024-01-30 07:50 UTC, Marymary-dev commented
@nobert-mumo , @cbrianbet  kind reminder to review this

2024-01-31 09:00 UTC, nobert-mumo commented
> @nobert-mumo , @cbrianbet kind reminder to review this

Sorry @Marymary-dev missed out on this; this is probably affected by the PatientPK in Ushauri discussions.?

2024-01-31 11:24 UTC, Marymary-dev commented
Yes it would be affected

2024-02-02 08:29 UTC, nobert-mumo commented on Scripts/REPORTING/load_aggregate_Ushauri_sms_reminders.sql
> +    Into   reporting.dbo.Aggregateushaurismsreminders
nitpik: we can have as CamelCase e.g. `AggregateUshauriSmsReminders`

2024-02-06 06:26 UTC, nobert-mumo approved these changes

2024-02-06 06:26 UTC, merged