Introduced a mhealth folder with scripts mapped to CT patient PK
palladiumkenya/dwh-etl pull request #362
Opened 2024-02-06 07:26 UTC by DennisGibz

2024-02-09 04:56 UTC, nobert-mumo commented
> 

@DennisGibz for the Ushauri changes maybe you can comment on the scripts to have more context as we review?

2024-02-09 05:05 UTC, nobert-mumo commented on Scripts/ODS/utils/COLUMN_HASHING/CT/HASH_PATIENTPK_PATIENTID/Update_PatientPKHash_PatientIDHash.sql
> -	--update ODS.dbo.CT_Patient
@DennisGibz just checking for this, we had commented out intentionally?

2024-02-09 06:01 UTC, DennisGibz commented on Scripts/ODS/utils/COLUMN_HASHING/CT/HASH_PATIENTPK_PATIENTID/Update_PatientPKHash_PatientIDHash.sql
> -	--update ODS.dbo.CT_Patient
It was commented (which should be the case) but with this PR it has been uncommented.

2024-02-09 08:46 UTC, DennisGibz commented
> > 
> 
> @DennisGibz for the Ushauri changes maybe you can comment on the scripts to have more context as we review?

1 1_RecreatePatient_PatientPKColumns and 2_RecreatePatientAppointments_PatientPKColumns
     -  The two scripts renames the PatientPK coming from ushauri to UShauri_patientPK and UShauri_PatientPKHash respectively.
     - The scripts also also creates new PatientPK and patientPKHash columns
2. 3_Update_PatientPatientPK and 4_Update_PatientAppointments_PatientPK 
   - The two scripts updates the above created patientPK with the PKs from C&T patients based on CCCNumber and Sitecode
   - Where no match, we retain what we got from ushauri then populate the patientPKHash

2024-02-09 09:52 UTC, nobert-mumo commented on Scripts/ODS/Mhealth/3_Update_PatientPatientPK.sql
> +
@DennisGibz for the hashing would it make sense to move this to the hashing folders, so we organize all hashing in one folder ?

2024-02-09 12:27 UTC, DennisGibz commented on Scripts/ODS/Mhealth/1_RecreatePatient_PatientPKColumns.sql
> +		IF NOT EXISTS (
Not at all. Just wanted to patientPK from ushauri and CT separated and downstream us the patientPK known to us without much confusion.

2024-02-09 12:31 UTC, DennisGibz commented on Scripts/ODS/Mhealth/3_Update_PatientPatientPK.sql
> +UPDATE a
Where patientPK from ushauri  doesnt exist in the CT docket it remains as is identified by emrType.

It's to simplify the analysis work and use just one column patientPK in the models.

2024-02-09 12:33 UTC, nobert-mumo commented on Scripts/ODS/Mhealth/3_Update_PatientPatientPK.sql
> +UPDATE a
ah okay, how would we differentiate the two patientPKs  from emr vs ushauri  in the downstream models ?

2024-02-09 12:42 UTC, DennisGibz commented on Scripts/ODS/Mhealth/3_Update_PatientPatientPK.sql
> +UPDATE a
> with this wouldn't it be a bit confusing to mix both patientPKs from ushauri & emr into one column?

Or where there is no match, we just leave it as null? It can still work by the way.

2024-02-10 08:37 UTC, nobert-mumo requested changes

2024-02-10 08:37 UTC, nobert-mumo commented on Scripts/ODS/Mhealth/1_RecreatePatient_PatientPKColumns.sql
> +BEGIN
@DennisGibz we could also add some comments here for future reference

2024-02-11 13:24 UTC, DennisGibz commented on Scripts/ODS/Mhealth/1_RecreatePatient_PatientPKColumns.sql
> +BEGIN
Managed to add the comments.

2024-02-11 13:24 UTC, DennisGibz commented on Scripts/ODS/Mhealth/3_Update_PatientPatientPK.sql
> +
Hashing now on mhealth folder under utils.

2024-02-11 17:02 UTC, nobert-mumo approved these changes
@DennisGibz please add comments on the 'RecreatePatient_PatientPKColumns' scripts to just highlight what the code is doing. Might not be oblivious to the naked eye. Otherwise, I think the other clarifications were addressed..

2024-02-11 18:23 UTC, merged