Mode some modification on the ODS and NDWH scripts resulting from the…
palladiumkenya/dwh-etl pull request #383
Opened 2024-03-05 12:27 UTC by DennisGibz

… last completed refresh

2024-03-06 12:51 UTC, cbrianbet approved these changes

2024-03-07 06:10 UTC, nobert-mumo requested changes

2024-03-07 06:10 UTC, nobert-mumo commented on Scripts/ODS/MNCH DOCKET/Load_MNCH_Heis.sql
>  					where HEIExitCritearia like '%Confirmed HIV Positive%')
@DennisGibz was wondering what the logic behind was where clause?

2024-03-07 06:10 UTC, nobert-mumo commented on Scripts/ODS/MNCH DOCKET/Load_MNCH_Heis.sql
> -					ROW_NUMBER() OVER (PARTITION BY P.PatientPK,P.SiteCode,HEIExitCritearia
@DennisGibz does it mean from the partition that was checking fro dups it was possible for a HEI to have two more than one `HEIExitCritearia`?

2024-03-07 07:35 UTC, DennisGibz commented on Scripts/ODS/CT_DOCKET/CT_PatientPharmacy.sql
> -				USING(SELECT Distinct top 20
Top 20 manenos. Kudos to my previous reviewers @nobert-mumo  and @cbrianbet

2024-03-07 07:44 UTC, DennisGibz commented on Scripts/ODS/MNCH DOCKET/Load_MNCH_Heis.sql
> -					ROW_NUMBER() OVER (PARTITION BY P.PatientPK,P.SiteCode,HEIExitCritearia
I think it was a data quality related problem that we were trying to address. I don't think where clause servers the purpose anymore.

2024-03-07 07:48 UTC, DennisGibz commented on Scripts/ODS/MNCH DOCKET/Load_MNCH_Heis.sql
> -					ROW_NUMBER() OVER (PARTITION BY P.PatientPK,P.SiteCode,HEIExitCritearia
tested by set removing the where clause and it has no impact on the result.

2024-03-07 07:50 UTC, DennisGibz commented on Scripts/NDWH/ALL DIMENSIONS/load_DimHTSTraceOutcome.sql
> +						Select
Added TracingOutcome IS NOT NULL to deal the dulpicates. However,we will continue monitoring using the metabase dashboard.

2024-03-07 08:05 UTC, Marymary-dev commented
Requesting visibility on this work on ODS @koskedk

2024-03-07 20:21 UTC, nobert-mumo approved these changes
LGTM

2024-03-08 07:16 UTC, merged