modified Intermediate_ViralLoadsIntervals to remove the PatientID on …
palladiumkenya/dwh-etl pull request #394
Opened 2024-03-18 12:33 UTC by DennisGibz

…the select distinct. Also modified DimHTSTraceOutcome and intoduced case statement to eliminate the duplicates

2024-03-21 14:21 UTC, nobert-mumo commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/load_intermediate_ViralLoadsIntervals.sql
> +	null As PatientID,
@DennisGibz why not remove the column entirely since it's not used anywhere ?

2024-03-21 14:21 UTC, nobert-mumo commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/load_intermediate_ViralLoadsIntervals.sql
>  	distinct_viral_load_clients.PatientIDHash,
@DennisGibz we also get rid of the hash yeah ?

2024-03-21 14:23 UTC, DennisGibz commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/load_intermediate_ViralLoadsIntervals.sql
>  	distinct_viral_load_clients.PatientIDHash,
I didn't want to break the etl during the hashing.

2024-03-21 14:26 UTC, nobert-mumo commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/load_intermediate_ViralLoadsIntervals.sql
>  	distinct_viral_load_clients.PatientIDHash,
ah okay, but wouldn't including PatientIDHash still result in dups ?

2024-03-21 14:28 UTC, DennisGibz commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/load_intermediate_ViralLoadsIntervals.sql
>  	distinct_viral_load_clients.PatientIDHash,
Yeah. Just exclude the column. I think we no longer have duplicates. I checked.

2024-03-21 14:30 UTC, nobert-mumo commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/load_intermediate_ViralLoadsIntervals.sql
>  	distinct_viral_load_clients.PatientIDHash,
sure, we can get rid of the patientId columns all together and have it clear in the code.

2024-04-03 16:25 UTC, nobert-mumo requested changes
@DennisGibz I think the PR has still some pending changes/

2024-04-11 10:03 UTC, nobert-mumo requested changes

2024-04-11 10:43 UTC, DennisGibz commented on Scripts/ODS/Mhealth/Load_Ushauri_PatientAppointments.sql
> +						-- a.[UshauriPatientPK]  = b.PatientPK
@nobert-mumo yes. The uniqueness is based on just Sitecode and AppointmentID. With the next release I will clean up the script.

2024-04-11 10:44 UTC, DennisGibz commented on Scripts/ODS/CT_DOCKET/Remove_CT_ODS_Duplicates/CT_Ipt.sql
> +						 ROW_NUMBER() OVER (PARTITION BY PatientPK,Sitecode,onTBDrugs,OnIPT,EverOnIPT,EvaluatedForIPT,TBScreening,VisitDateORDER BY
@nobert-mumo thanks for noticing above. I have edited the script.

2024-04-11 10:45 UTC, DennisGibz commented on Scripts/REPORTING/load_aggregate_ushauri_appointments.sql
> -             From   ndwh.dbo.FactUshauriAppointments Sms
I don't remember modifying anything on the above script. I even tried to resolve the conflict by taking everything from the remote.

2024-04-16 05:20 UTC, nobert-mumo requested changes

2024-04-16 05:20 UTC, nobert-mumo commented on Scripts/ODS/CT_DOCKET/Remove_CT_ODS_Duplicates/CT_Ipt.sql
> +						 ROW_NUMBER() OVER (PARTITION BY PatientPK,Sitecode,onTBDrugs,OnIPT,EverOnIPT,EvaluatedForIPT,TBScreening,VisitDateORDER BY
@DennisGibz I think the typo is still present ?

2024-04-16 05:20 UTC, nobert-mumo commented on Scripts/REPORTING/load_aggregate_ushauri_appointments.sql
> -             From   ndwh.dbo.FactUshauriAppointments Sms
@DennisGibz with this change the script will fail I believe. I guess we have to resolve the conflicts.

2024-04-29 11:30 UTC, closed without merging