Adding PrepEnrollmentDate to the Fact and the Linelist
palladiumkenya/dwh-etl pull request #396
Opened 2024-03-21 14:10 UTC by Marymary-dev

2024-03-21 14:17 UTC, nobert-mumo commented on Scripts/NDWH/PREP_FACT_TABLES/load_FactPrepAssessments.sql
> +left join NDWH.dbo.DimDate as prep_enrol_Date on prep_enrol_Date.Date = source_data.PrepEnrollmentDate
@Marymary-dev I know we have a similar field on DimPatient. Would this be any different ?

2024-03-21 14:18 UTC, Marymary-dev commented
is it, let me check that

2024-03-25 20:19 UTC, nobert-mumo commented on Scripts/REPORTING/load_Linelist_Prep.sql
> +        prepEnrol.DateKey as PrepEnrollmentDate
@Marymary-dev I thought the idea behind join to the date dimension is to pick the corresponding date field ?

2024-04-03 16:32 UTC, nobert-mumo requested changes

2024-04-03 16:32 UTC, nobert-mumo commented on Scripts/REPORTING/load_Linelist_Prep.sql
> +        prepEnrol.DateKey as PrepEnrollmentDate
@Marymary-dev  I think if you pick `prepEnrol.Date` here then we don't have to cast to date down there.

2024-04-04 08:34 UTC, Marymary-dev commented on Scripts/REPORTING/load_Linelist_Prep.sql
> +        prepEnrol.DateKey as PrepEnrollmentDate
> @Marymary-dev I think if you pick `prepEnrol.Date` here then we don't have to cast to date down there.

@nobert-mumo  this has been corrected

2024-04-04 10:28 UTC, nobert-mumo requested changes

2024-04-04 10:28 UTC, nobert-mumo commented on Scripts/REPORTING/load_Linelist_Prep.sql
> +        cast (prepEnrol.DateKey as date) as PrepEnrollmentDate
@Marymary-dev rem to change to `prepEnrol.Date as PrepEnrollmentDate`

2024-04-04 12:49 UTC, Marymary-dev commented on Scripts/REPORTING/load_Linelist_Prep.sql
> +        cast (prepEnrol.DateKey as date) as PrepEnrollmentDate
Okay, this has been picked @nobert-mumo

2024-04-04 17:15 UTC, merged