Creating Fact Modules Uptake
palladiumkenya/dwh-etl pull request #399
Opened 2024-03-28 18:42 UTC by Marymary-dev

2024-04-03 16:48 UTC, nobert-mumo commented on Scripts/NDWH/C&T FACT TABLES/load_FactModulesUptake.sql
> +             Where  Datediff(Month, Visitdate, Eomonth( Dateadd(Mm, -1, Getdate())))  <= 12
@Marymary-dev for this should we include a check for RiskCategorization to identify ML ?

2024-04-03 16:53 UTC, nobert-mumo commented
@Marymary-dev  the logic looks good to me. Only had a few questions/comments:
- I see the fact is an aggregate at partner level. Any reservations on having it a facility level?
- If we go facility level would it make sense to add modules uptake to the EMR Line list instead of creating a new table?

2024-04-04 08:46 UTC, Marymary-dev commented
> @Marymary-dev the logic looks good to me. Only had a few questions/comments:
> 
> * I see the fact is an aggregate at partner level. Any reservations on having it a facility level?
> * If we go facility level would it make sense to add modules uptake to the EMR Line list instead of creating a new table?

@nobert-mumo  the fact is at partner and county level. The uptake cannot be at facility level since we would need to compute the uptake for the different program areas.

2024-04-04 08:56 UTC, Marymary-dev commented on Scripts/NDWH/C&T FACT TABLES/load_FactModulesUptake.sql
> +             Where  Datediff(Month, Visitdate, Eomonth( Dateadd(Mm, -1, Getdate())))  <= 12
@nobert-mumo  this has been included

2024-04-05 09:46 UTC, nobert-mumo commented on Scripts/NDWH/C&T FACT TABLES/load_FactModulesUptake.sql
> +                   Sdp,
@Marymary-dev for the CTEs maybe we can omit the sdp, sdp_Agency, county and sub county to make the code smaller. Then we can get these columns back in the main select.

2024-04-05 09:49 UTC, nobert-mumo requested changes
@Marymary-dev for the CTEs maybe we can omit the sdp, sdp_Agency, county and sub county to make the code smaller. Then we can get these columns back in the main select.

2024-04-05 10:53 UTC, Marymary-dev commented
> @Marymary-dev for the CTEs maybe we can omit the sdp, sdp_Agency, county and sub county to make the code smaller. Then we can get these columns back in the main select.

@nobert-mumo  this has been cleaned

2024-04-08 08:22 UTC, nobert-mumo approved these changes
LGTM @Marymary-dev, I guess the reporting table will be in another PR..

2024-04-08 08:55 UTC, Marymary-dev commented
Sure, look out for line list Module uptake in another PR

2024-04-08 09:00 UTC, merged