Create Fact Visits for the last 12 months
palladiumkenya/dwh-etl pull request #442
Opened 2024-06-25 07:31 UTC by Marymary-dev

2024-06-25 08:25 UTC, nobert-mumo commented on Scripts/NDWH/C&T FACT TABLES/load_FactVisits.sql
> +WHERE patient.voided =0 and  VisitDate >= EOMONTH(DATEADD(MONTH, -12, GETDATE()))
@Marymary-dev I think we need to filter voided records in visits also?

2024-06-25 08:25 UTC, nobert-mumo commented on Scripts/NDWH/C&T FACT TABLES/load_FactVisits.sql
> +WHERE patient.voided =0 and  VisitDate >= EOMONTH(DATEADD(MONTH, -12, GETDATE()))
@Marymary-dev for the eomonth we should consider last completed month perhaps ?

2024-06-25 18:42 UTC, Marymary-dev commented on Scripts/NDWH/C&T FACT TABLES/load_FactVisits.sql
> +WHERE patient.voided =0 and  VisitDate >= EOMONTH(DATEADD(MONTH, -12, GETDATE()))
@nobert-mumo  for the missed opportunities chart we are charting the last 12 months , voided has been considered

2024-06-26 20:16 UTC, nobert-mumo commented on Scripts/NDWH/C&T FACT TABLES/load_FactVisits.sql
> +WHERE patient.voided =0 and  VisitDate >= EOMONTH(DATEADD(MONTH, -12, GETDATE()))
@Marymary-dev I meant we might need to have `visits.voided` = 0 ?

2024-06-26 20:43 UTC, Marymary-dev commented on Scripts/NDWH/C&T FACT TABLES/load_FactVisits.sql
> +WHERE patient.voided =0 and  VisitDate >= EOMONTH(DATEADD(MONTH, -12, GETDATE()))
@nobert-mumo  , thanks , this has been filtered out

2024-06-27 12:50 UTC, nthusi-codes requested changes

2024-06-27 12:50 UTC, nthusi-codes commented on Scripts/NDWH/C&T FACT TABLES/load_FactHistoricalViralLoads.sql
> +into NDWH.dbo.FactVLLastThreeYears
Table should be last two years I believe

2024-06-27 12:50 UTC, nthusi-codes commented on Scripts/NDWH/C&T FACT TABLES/load_FactHistoricalViralLoads.sql
> +alter table NDWH.dbo.FactVLLastThreeYears add primary key(FactKey);
Table should be last 2 years

2024-06-28 06:32 UTC, Marymary-dev commented on Scripts/NDWH/C&T FACT TABLES/load_FactHistoricalViralLoads.sql
> +into NDWH.dbo.FactVLLastThreeYears
@nthusi-codes  the changes have been made

2024-07-11 14:18 UTC, nobert-mumo commented on Scripts/NDWH/C&T FACT TABLES/load_FactVisits.sql
> +	DROP TABLE NDWH.[dbo].[FactVisits];
@Marymary-dev consider renaming to `FactHistoricalVisits` to be consistent with the the viral load one

2024-07-11 14:49 UTC, Marymary-dev commented
Rename has been effected

2024-07-15 17:26 UTC, Marymary-dev commented on Scripts/NDWH/C&T FACT TABLES/load_FactVisits.sql
> +	DROP TABLE NDWH.[dbo].[FactVisits];
@nobert-mumo  the renaming has been effected

2024-07-18 11:48 UTC, nobert-mumo commented on Scripts/NDWH/C&T FACT TABLES/load_FactVisits.sql
> +	DROP TABLE NDWH.[dbo].[FactVisits];
Sorry Mary meant `FactHistoricalVisitsLastTwoYears` or `FactHistoricalVisitsLastOneYear` (depending on how far we want to go). Although in the long run we will document the dimensional layer it might be worthwhile to give the table a more descriptive name.

2024-07-22 09:39 UTC, Marymary-dev commented
@nobert-mumo  and @DennisGibz  kindly review this

2024-09-09 16:33 UTC, Marymary-dev commented
> @nobert-mumo and @DennisGibz kindly review this

@nobert-mumo  and @DennisGibz  polite reminder

2024-09-30 09:47 UTC, Marymary-dev commented on Scripts/NDWH/C&T FACT TABLES/load_FactHistoricalViralLoads.sql
> +into NDWH.dbo.FactVLLastThreeYears
> Table should be last two years I believe

@nthusi-codes  the change requested were made. The table has 2 years of records

2025-01-06 08:25 UTC, nobert-mumo approved these changes
@Marymary-dev  LGTM!

2025-01-06 09:25 UTC, Marymary-dev commented
> @Marymary-dev LGTM!

@nthusi-codes  kindly review this

2025-01-14 14:17 UTC, nthusi-codes approved these changes

2025-01-14 14:18 UTC, merged