Adding Missed opportunities VL gap model
palladiumkenya/dwh-etl pull request #448
Opened 2024-06-27 20:47 UTC by Marymary-dev

2024-06-28 08:45 UTC, nobert-mumo approved these changes

2024-06-28 08:45 UTC, nobert-mumo commented on Scripts/REPORTING/load_cs_missed_opportunities_vl_gap.sql
> +With Mfl_partner_agency_combination
@Marymary-dev at reporting layer level do we need to have this CTE? Since we already have PartnerKey & AgencyKey on the facts ?

2024-06-28 08:46 UTC, nobert-mumo reviewed
Sorry meant to comment instead of approve

2024-06-28 09:44 UTC, nobert-mumo requested changes

2024-06-28 09:44 UTC, nobert-mumo commented on Scripts/REPORTING/load_cs_missed_opportunities_vl_gap.sql
> +                           And Recent.Orderedbydate Not Between
@Marymary-dev are we using `not between` so that we get invalid vl ? I think we might need to rename the CTE to invalid_vl for more clarity maybe ?

2024-06-28 09:44 UTC, nobert-mumo commented on Scripts/REPORTING/load_cs_missed_opportunities_vl_gap.sql
> +                           And Recent.Orderedbydate Not Between
@Marymary-dev line 95 to 100 looks like duplicated?

2024-06-28 09:46 UTC, nthusi-codes approved these changes

2024-07-01 06:55 UTC, Marymary-dev commented on Scripts/REPORTING/load_cs_missed_opportunities_vl_gap.sql
> +With Mfl_partner_agency_combination
Thanks, the CTE has been removed @nobert-mumo

2024-07-01 06:58 UTC, Marymary-dev commented on Scripts/REPORTING/load_cs_missed_opportunities_vl_gap.sql
> +                           And Recent.Orderedbydate Not Between
Renaming to Invalidity_for_VL effected @nobert-mumo

2024-07-01 07:09 UTC, Marymary-dev commented on Scripts/REPORTING/load_cs_missed_opportunities_vl_gap.sql
> +                           And Recent.Orderedbydate Not Between
> @Marymary-dev line 95 to 100 looks like duplicated?

The duplicated line of code has also been removed

2024-07-01 07:37 UTC, cbrianbet approved these changes

2024-07-02 15:57 UTC, cbrianbet approved these changes

2024-07-08 06:41 UTC, nobert-mumo requested changes

2024-07-08 06:41 UTC, nobert-mumo commented on Scripts/REPORTING/load_cs_missed_opportunities_vl_gap.sql
> +                Agegroup.Mohagegroup
@Marymary-dev we are changing from DATIM Age Group to MoH Age Group ?

2024-07-09 16:40 UTC, Marymary-dev commented on Scripts/REPORTING/load_cs_missed_opportunities_vl_gap.sql
> +                Agegroup.Mohagegroup
@nobert-mumo  this has been changed

2024-07-15 17:29 UTC, Marymary-dev commented on Scripts/REPORTING/load_cs_missed_opportunities_vl_gap.sql
> +                Agegroup.Mohagegroup
@nobert-mumo  requesting re-review

2024-07-18 11:44 UTC, nobert-mumo approved these changes
LGTM.

2024-07-22 09:38 UTC, merged