Feature/Adding-new-reporting-for-on-ART--sentinel-event
palladiumkenya/dwh-etl pull request #449
Opened 2024-07-02 09:30 UTC by nobert-mumo

This PR introduces a new  case surveillance reporting table to answer onART numbers longitudinally.

2024-07-02 11:51 UTC, Marymary-dev approved these changes

2024-07-02 13:30 UTC, cbrianbet commented on Scripts/REPORTING/load_cs_aggregate_onART_sentinel_event.sql
> +	drop TABLE [HIVCaseSurveillance].[dbo].[CsAggegateOnARTSentinelEvent]
Just a nitpick this should be **Aggregate** I see it created 2 tables on .83

2024-07-03 18:55 UTC, Marymary-dev requested changes
@nobert-mumo  the numbers for onART should be the numbers on ART AsofDate for the selected Cohort

2024-07-08 06:50 UTC, nobert-mumo commented on Scripts/REPORTING/load_cs_aggregate_onART_sentinel_event.sql
> +	drop TABLE [HIVCaseSurveillance].[dbo].[CsAggegateOnARTSentinelEvent]
@cbrianbet thanks. This is updated. I will drop the outdated table in the DB.

2024-07-08 06:51 UTC, nobert-mumo commented
> @nobert-mumo the numbers for onART should be the numbers on ART AsofDate for the selected Cohort

@Marymary-dev just confirming this means we should show cummulative As Of ?

2024-07-08 18:51 UTC, Marymary-dev commented
yes, sorry had not seen this

2024-07-11 13:52 UTC, nobert-mumo commented
> yes, sorry had not seen this

Hi @Marymary-dev this is updated we know have running totals for Started on ART Clients for the last 12 months from the reporting period

2024-07-15 17:53 UTC, Marymary-dev approved these changes
Will borrow a lot from the cursor object. Just thinking aloud if this table can be reused by many other tables

2024-07-17 12:42 UTC, nobert-mumo commented
> Will borrow a lot from the cursor object. Just thinking aloud if this table can be reused by many other tables

Indeed can be reused. Will now merge

2024-07-17 12:42 UTC, merged