Hiv cs tx continuity
palladiumkenya/dwh-etl pull request #451
Opened 2024-07-03 16:04 UTC by DennisGibz

2024-07-08 05:47 UTC, nobert-mumo commented on Scripts/REPORTING/HIVCaseSurveillance/load_cs_TxContinuity.sql
> +			,FactARTHistory.AgeGroup
@DennisGibz not sure, I thought since this is a Fact we should be using an AgeGroupKey?

2024-07-08 05:48 UTC, nobert-mumo requested changes
@DennisGibz not sure, I thought since this is a Fact we should be using an AgeGroupKey?

2024-07-08 06:18 UTC, DennisGibz commented
@nobert-mumo yes but DimAgegroup was bringing about discrepancy in numbers. We have changed the report to be a linelist.

2024-07-08 06:26 UTC, nobert-mumo commented
> @nobert-mumo yes but DimAgegroup was bringing about discrepancy in numbers. We have changed the report to be a linelist.

@DennisGibz not sure I follow, do you mean we changed the fact to a report ?

2024-07-15 18:25 UTC, Marymary-dev reviewed
Ensure the CohortYearMonth is set to EndofMonth for ease of filtering

2024-07-15 18:25 UTC, Marymary-dev commented on Scripts/REPORTING/HIVCaseSurveillance/load_cs_TxContinuity.sql
>  			,TRY_CAST(DateConfirmedHIVPositiveKey AS DATETIME2) As CohortYearMonth
Ensure the CohortYearMonth is set to EndofMonth for ease of filtering

2024-07-22 06:50 UTC, DennisGibz commented
> > @nobert-mumo yes but DimAgegroup was bringing about discrepancy in numbers. We have changed the report to be a linelist.
> 
> @DennisGibz not sure I follow, do you mean we changed the fact to a report ?

@nobert-mumo  this was never a fact. We have factARTHistory as the source fact.

2024-07-22 07:56 UTC, DennisGibz commented on Scripts/REPORTING/HIVCaseSurveillance/load_cs_TxContinuity.sql
>  			,TRY_CAST(DateConfirmedHIVPositiveKey AS DATETIME2) As CohortYearMonth
@Marymary-dev this has since been addressed.

2024-07-22 08:07 UTC, nobert-mumo commented
> > > @nobert-mumo yes but DimAgegroup was bringing about discrepancy in numbers. We have changed the report to be a linelist.
> > 
> > 
> > @DennisGibz not sure I follow, do you mean we changed the fact to a report ?
> 
> @nobert-mumo this was never a fact. We have factARTHistory as the source fact.

@DennisGibz I thought [NDWH].[dbo].[FactARTHistory] is a fact ? then we should be having an `AgeGroupKey` that we join to `DimAgeGroup` when building the report.

2024-07-22 08:09 UTC, DennisGibz commented
> > > > @nobert-mumo yes but DimAgegroup was bringing about discrepancy in numbers. We have changed the report to be a linelist.
> > > 
> > > 
> > > @DennisGibz not sure I follow, do you mean we changed the fact to a report ?
> > 
> > 
> > @nobert-mumo this was never a fact. We have factARTHistory as the source fact.
> 
> @DennisGibz I thought [NDWH].[dbo].[FactARTHistory] is a fact ? then we should be having an `AgeGroupKey` that we join to `DimAgeGroup` when building the report.

Yeah. We can have the dim attached to the fact then consume the column downstream. I'll look at that.

2024-08-13 09:44 UTC, nobert-mumo commented
@DennisGibz , the table `FactARTHistory` seems to be a bit off from being a fact table? I think we need to design not to have the table denormalized but only contain the foreign dim keys

2025-01-16 10:00 UTC, DennisGibz commented
The PR has since been modified @nobert-mumo , @Marymary-dev , @cbrianbet

2025-01-16 12:30 UTC, nobert-mumo requested changes

2025-01-16 12:30 UTC, nobert-mumo commented on Scripts/REPORTING/HIVCaseSurveillance/load_cs_TxContinuity.sql
>  			,COUNT(1) AS NoOfClients
@DennisGibz, do we need this column here since this is a patient level dataset ?

2025-01-16 12:30 UTC, nobert-mumo commented on Scripts/REPORTING/HIVCaseSurveillance/load_cs_TxContinuity.sql
> +			,FactARTHistory.AgeGroup
@DennisGibz please recheck on this.

2025-07-08 07:03 UTC, nobert-mumo commented on Scripts/REPORTING/HIVCaseSurveillance/load_cs_TxContinuity.sql
> +		WHERE Facility.MFLCode IS NOT NULL AND FactARTHistory.ARTOutcomeKey in (2,3,6,8)
@DennisGibz maybe we can replace the ARTOutcome with ARTOutcomeDescription so that it 'easily observable'? I know the DimKey don't change but the description would be better IMO.

2025-07-08 07:17 UTC, nobert-mumo commented
@DennisGibz the model seems to contain duplicates for Patient, AsOfDate combinations, can you re-check?

`select 
    PatientPKHash,
    MFLCode,
    asofdate,
    count(*) as count
from [HIVCaseSurveillance].[dbo].[CsTxContinuity]
group by 
    PatientPKHash,
    MFLCode,
    asofdate
having count(*) > 1`
![image](https://github.com/user-attachments/assets/fd4468d9-d04d-4494-9b8c-651c5f2aea4c)

2025-07-23 05:58 UTC, nobert-mumo approved these changes
LGTM

2025-07-23 06:37 UTC, DennisGibz commented
@Marymary-dev  uko na maoni?

2025-07-25 07:16 UTC, merged