Filtering out Lost in HMIS for sites not reported
palladiumkenya/dwh-etl pull request #453
Opened 2024-07-10 19:14 UTC by Marymary-dev

2024-07-11 14:12 UTC, nobert-mumo commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/4_load_intermediate_ARTOutcomes.sql
> +THEN 'LostinHMIS'
@Marymary-dev I was wondering is it expected all facilities upload data between 1st and 15th or some can upload in the last week of the month ?

I think we need to also update the Dim ARTOutcome with the new status

2024-07-11 14:50 UTC, Marymary-dev commented
All facilities should upload data between 1st and 15th and not the last day of the previous month

2024-07-15 18:29 UTC, Marymary-dev commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/4_load_intermediate_ARTOutcomes.sql
> +THEN 'LostinHMIS'
@nobert-mumo  requesting a re-review

2024-07-16 05:14 UTC, nobert-mumo requested changes

2024-07-16 05:14 UTC, nobert-mumo commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/4_load_intermediate_ARTOutcomes.sql
> +THEN 'Lost in HMIS'
@Marymary-dev I believe this should be `LHMIS` and not `Lost in HMIS` in order for it to be joined on the Dim ARTOutcome ?

2024-07-16 05:14 UTC, nobert-mumo commented on Scripts/NDWH/ALL DIMENSIONS/STATIC DIMENSIONS/load_DimARTOutcome.sql
>  		select'uL' as ARTOutcome
@Marymary-dev @DennisGibz Not sure if this folder is part of the data pipelines or we need to run the changes manually ?

2024-07-16 10:28 UTC, closed without merging