Added FactHistoricalViralLoad script. Yet to add PBFW logi
palladiumkenya/dwh-etl pull request #454
Opened 2024-07-15 06:48 UTC by DennisGibz

2024-07-15 18:42 UTC, Marymary-dev reviewed
@DennisGibz   the logic is incorrect here, you are saying if datediff ordered date and asof <12 and they are adults then they have invalid vls which is wrong, we can link up kesho to discuss this

2024-07-15 18:42 UTC, Marymary-dev commented on Scripts/NDWH/C&T FACT TABLES/FactHistoricalViralLoad.sql
> +						WHEN datediff(month,[OrderedbyDate],@as_of_date) <= 12 and  Datediff(year,Patient.DOB,@as_of_date) > 24 THEN 1
@DennisGibz  the logic is incorrect here, you are saying if datediff ordered date and asof <12 and they are adults then they have invalid vls which is wrong, we can link up kesho to discuss this

2025-01-06 09:39 UTC, nobert-mumo requested changes

2025-01-06 09:39 UTC, nobert-mumo commented on Scripts/NDWH/C&T FACT TABLES/FactHistoricalViralLoad.sql
> +TRUNCATE TABLE ndwh.dbo.FactViralLoad_Hist;
@DennisGibz just curious, why have two truncate statements for the same table in the script?

2025-01-16 09:53 UTC, DennisGibz commented on Scripts/NDWH/C&T FACT TABLES/FactHistoricalViralLoad.sql
> +TRUNCATE TABLE ndwh.dbo.FactViralLoad_Hist;
Check the most recent release. "Placed the fact tables....."

2025-01-20 11:28 UTC, DennisGibz commented
@nobert-mumo the file should now be okay with the most recent released PR. 24 months factored in, Script renamed and double scripting removed

2025-01-20 14:12 UTC, DennisGibz commented
@cbrianbet confirm if #538 is in use by superset. I remember the model was there for a purpose. If its redundant we can drop it from the PRs.

2025-01-22 11:45 UTC, Marymary-dev commented on Scripts/NDWH/C&T FACT TABLES/FactViralLoad_Historical.sql
> +										CohortYearMonth,
Please add AgencyKey

2025-01-23 06:37 UTC, DennisGibz commented on Scripts/NDWH/C&T FACT TABLES/FactViralLoad_Historical.sql
> +										CohortYearMonth,
Well noted @Marymary-dev

2025-01-28 13:16 UTC, DennisGibz commented
Adjusted the two scripts to align with new changes.

2025-01-28 14:18 UTC, Marymary-dev commented on Scripts/NDWH/C&T FACT TABLES/FactViralLoad_Hist.sql
> +		ReportedbyDate.DateKey as ReportedbyDateKey,
@DennisGibz  youvhave left out Gender and CohortYearMonth

2025-01-29 07:35 UTC, DennisGibz commented on Scripts/NDWH/C&T FACT TABLES/FactViralLoad_Hist.sql
> +		ReportedbyDate.DateKey as ReportedbyDateKey,
@Marymary-dev with the patientKey you can get the two from dimPatient

2025-01-29 08:09 UTC, nobert-mumo commented on Scripts/NDWH/C&T FACT TABLES/FactViralLoad_Hist.sql
> +		ReportedbyDate.DateKey as ReportedbyDateKey,
@DennisGibz @Marymary-dev I agree at the fact level, if we have the dim patient link in the fact then that should be sufficient

2025-01-29 08:19 UTC, nobert-mumo approved these changes
LGTM @DennisGibz!
Would be nice to recheck if the underlying reporting tables are impacted by the fact changes.

2025-01-30 07:53 UTC, merged