Added a new intermediate table to calculate PBFW. The script has comm…
palladiumkenya/dwh-etl pull request #481
Opened 2024-08-02 18:48 UTC by DennisGibz

…ents inside just to explain all the processes. If agreed apon,all the references for PBFW within other facts tables

2024-08-13 10:38 UTC, nobert-mumo requested changes

2024-08-13 10:38 UTC, nobert-mumo commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/Load_Intermediate_PregnantAndBreastFeeding.sql
> +SELECT @start_date = dateadd(month, -0, eomonth(dateadd(month, -2, getdate())));
@DennisGibz this should go back 12 months yeah?

2024-08-13 10:38 UTC, nobert-mumo commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/Load_Intermediate_PregnantAndBreastFeeding.sql
> +BreastFeedingFromPregnantOrdered As (---6,365
forgotten comment perhaps ? :)

2024-08-13 10:38 UTC, nobert-mumo commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/Load_Intermediate_PregnantAndBreastFeeding.sql
> +      ,[IsBreastFeedingAsOfDate]
@DennisGibz  maybe we can have this column name as just `IsBreastFeeding`  since we akready have an AsofDate column

2024-08-14 07:33 UTC, DennisGibz commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/Load_Intermediate_PregnantAndBreastFeeding.sql
> +SELECT @start_date = dateadd(month, -0, eomonth(dateadd(month, -2, getdate())));
This has since been been addressed @nobert-mumo . Thank you.

2024-08-16 07:46 UTC, nobert-mumo approved these changes

2024-08-20 08:48 UTC, merged