Modified load_Intermediate_PregnantAndBreastfeeding script
palladiumkenya/dwh-etl pull request #497
Opened 2024-08-29 15:26 UTC by DennisGibz

2024-09-02 19:28 UTC, nobert-mumo commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/Load_Intermediate_PregnantAndBreastFeeding.sql
> +  FROM PBFW where [SiteCode] is not null
@DennisGibz why would this happen? Could we be omitting genuine clients ?

2024-09-02 19:28 UTC, nobert-mumo commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/Load_Intermediate_PregnantAndBreastFeeding.sql
> +	   from MaxOrderedCombineBreastFeeding
Nice one with the full join. Just curious how did we handle the duplicates we were getting even after changing from `union` to `full join` ?

2024-09-30 06:22 UTC, nobert-mumo commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/Load_Intermediate_PregnantAndBreastFeeding.sql
> +  FROM PBFW where [SiteCode] is not null
@DennisGibz, this is still pending right ?

2024-09-30 11:25 UTC, nthusi-codes requested changes

2024-12-03 08:00 UTC, DennisGibz commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/Load_Intermediate_PregnantAndBreastFeeding.sql
> +  FROM PBFW where [SiteCode] is not null
@nobert-mumo I don't think they are genuine records. I have re-run the script step by step and seems like the full outer join is causing the nulls.
See sample outputs below;

![image](https://github.com/user-attachments/assets/73337834-5e10-43d8-9379-e7e9a6b03d93)

2024-12-03 08:06 UTC, DennisGibz commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/Load_Intermediate_PregnantAndBreastFeeding.sql
> +	   from MaxOrderedCombineBreastFeeding
The full outer join works well but to remove dups but the unmapped patients are left with nulls. Thats why I am using the where sitecode is not null to eliminate the nulls

2024-12-03 08:07 UTC, DennisGibz commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/Load_Intermediate_PregnantAndBreastFeeding.sql
>  ),
Well noted @nthusi-codes . I'll clean up the script.

2024-12-03 09:27 UTC, nobert-mumo requested changes

2024-12-03 09:27 UTC, nobert-mumo commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/Load_Intermediate_PregnantAndBreastFeeding.sql
> +	   from MaxOrderedCombineBreastFeeding
@DennisGibz not sure I follow, coz with full join, I expected we would have coalesce in the column section to take care of nulls. 

e.g. `coalesce(MaxOrderedCombineBreastFeeding.SiteCode, PregnantAsOfDate.SiteCode) as SiteCode`

Also not sure the full join would eliminate the dups ?

2024-12-03 09:27 UTC, nobert-mumo commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/Load_Intermediate_PregnantAndBreastFeeding.sql
> +  FROM PBFW where [SiteCode] is not null
@DennisGibz I still think is related to the full join up there.

2024-12-18 20:00 UTC, nobert-mumo approved these changes
@DennisGibz apart from the small comment on the duplicate code, majorly LGTM

2024-12-18 20:07 UTC, DennisGibz commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/Load_Intermediate_PregnantAndBreastFeeding.sql
> +insert into [ODS].[Intermediate].[Intermediate_PregnantAndBreastFeeding]([SiteCode],[PatientPK],PatientPKHash,[IsPregnant],[IsBreastFeeding],[AsOfDate],BreastFeedingRelatedVisitDate,PregnancyRelatedV
Not sure how you are getting above. Below is a screenshot of the results that I have

![image](https://github.com/user-attachments/assets/3c92562d-3fea-4d3d-bedf-025eb610d605)

2024-12-18 20:10 UTC, nobert-mumo commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/Load_Intermediate_PregnantAndBreastFeeding.sql
> +insert into [ODS].[Intermediate].[Intermediate_PregnantAndBreastFeeding]([SiteCode],[PatientPK],PatientPKHash,[IsPregnant],[IsBreastFeeding],[AsOfDate],BreastFeedingRelatedVisitDate,PregnancyRelatedV
> Not sure how you are getting above. Below is a screenshot of the results that I have
> 
> ![image](https://private-user-images.githubusercontent.com/87817387/397096371-3c92562d-3fea-4d3d-bedf-025eb610d605.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1NTI4MjMsIm5iZiI6MTczNDU1MjUyMywicGF0aCI6Ii84NzgxNzM4Ny8zOTcwOTYzNzEtM2M5MjU2MmQtM2ZlYS00ZDNkLWJlZGYtMDI1ZWI2MTBkNjA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDIwMDg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2NDk2OWExZGRkNmI0ZWE4ZGU4ZmMzNzUzN2I5YjYwOWFiOWRlNDc0ODdmMmRlMGU4OTRjOWRhNmRkZmI0OGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LLvH1njSHISswskOVnLH5LKT9tMtimvECBf9QTyDkhc)

@DennisGibz not really, I meant duplicated code on line 327 and 328, that would throw an error when the table is building right ?

2024-12-18 20:14 UTC, DennisGibz commented on Scripts/ODS/load_intermediate_tables/CT_intermediate_tables/Load_Intermediate_PregnantAndBreastFeeding.sql
> +insert into [ODS].[Intermediate].[Intermediate_PregnantAndBreastFeeding]([SiteCode],[PatientPK],PatientPKHash,[IsPregnant],[IsBreastFeeding],[AsOfDate],BreastFeedingRelatedVisitDate,PregnancyRelatedV
Surprisingly I wasn't throwing any errors...I have removed it though. Thanks

2024-12-20 07:10 UTC, nthusi-codes approved these changes

2024-12-20 07:13 UTC, merged