Cryptococal menengitis screening variables
palladiumkenya/dwh-etl pull request #500
Opened 2024-09-09 14:53 UTC by Marymary-dev

2024-09-10 05:29 UTC, nobert-mumo commented on Scripts/NDWH/C&T FACT TABLES/load_FactART.sql
> +    where   try_cast (TestResult as decimal) > 1000 and  rank=1
@Marymary-dev is it specific here to use Un suppression of   > 1000 copies?

2024-09-10 05:31 UTC, nobert-mumo requested changes

2024-09-10 05:31 UTC, nobert-mumo commented on Scripts/NDWH/C&T FACT TABLES/load_FactART.sql
> +),
@Marymary-dev I think for the longitudinal datasets we have to partition or something to make sure we don't introduce dups

2024-09-16 09:04 UTC, DennisGibz reviewed
I have tested the scripts and its taking too long to run. 2hrs and it hasn't finished.

2024-09-16 12:50 UTC, DennisGibz approved these changes
I have tested the scripts and its taking too long to run. 2hrs and it hasn't finished.

2024-09-16 13:05 UTC, Marymary-dev commented
@DennisGibz  it is taking approximately 47 minutes to run

2024-09-16 13:34 UTC, DennisGibz approved these changes

2024-09-16 13:35 UTC, cbrianbet approved these changes

2024-09-16 17:06 UTC, nobert-mumo approved these changes

2024-09-16 17:06 UTC, nobert-mumo commented on Scripts/NDWH/C&T FACT TABLES/load_FactART.sql
> +),
@Marymary-dev would this be viable ?

2024-09-18 13:54 UTC, merged