WIP Sentinel Events model
palladiumkenya/dwh-etl pull request #510
Opened 2024-10-02 13:16 UTC by Marymary-dev

2024-10-11 07:21 UTC, nobert-mumo commented on Scripts/REPORTING/HIVCaseSurveillance/load_cs_sentinel_events
> +    from ODS.dbo.All_EMRSites
@Marymary-dev I see we have this here to get the Agency & Partner, but I was wondering if its necessary since we are already getting the data from the dimensional layer ?

2024-10-11 07:21 UTC, nobert-mumo commented on Scripts/REPORTING/HIVCaseSurveillance/load_cs_sentinel_events
> +    NDWH.dbo.FactOrderedViralLoads as viralloads
@Marymary-dev not a very strong opinion, but I still think we can consider extending the already existing FactViralLoad  to get the extra viral loads.

2024-10-11 17:28 UTC, Marymary-dev commented on Scripts/REPORTING/HIVCaseSurveillance/load_cs_sentinel_events
> +    from ODS.dbo.All_EMRSites
@nobert-mumo , thanks, this has been removed

2024-10-11 17:29 UTC, Marymary-dev commented on Scripts/REPORTING/HIVCaseSurveillance/load_cs_sentinel_events
> +    NDWH.dbo.FactOrderedViralLoads as viralloads
@nobert-mumo  to be safe, since we don't know how the request will change, we had better have a Fact for the viral loads

2024-12-18 13:27 UTC, kevlanyo approved these changes

2024-12-20 09:33 UTC, nobert-mumo requested changes
@Marymary-dev maybe we can consider moving the suppression logic up further to the fact level?
I also rem having the discussion around utilizing the existing Fact Viral load to avoid duplication of logic across the facts perhaps.

2025-01-14 14:19 UTC, nthusi-codes approved these changes

2025-01-17 14:31 UTC, Marymary-dev commented on Scripts/REPORTING/HIVCaseSurveillance/load_cs_sentinel_events.sql
> +    WHEN (Isnumeric(Testresult) = 1 AND Cast(Replace(Testresult, ',', '') AS Float) < 200.00)
@nobert-mumo  this has been refactored to read from FactViral load

2025-01-20 09:21 UTC, cbrianbet approved these changes

2025-01-20 10:47 UTC, Marymary-dev commented
> @Marymary-dev maybe we can consider moving the suppression logic up further to the fact level? I also rem having the discussion around utilizing the existing Fact Viral load to avoid duplication of logic across the facts perhaps.

Hi @nobert-mumo  kindly review

2025-01-20 13:10 UTC, nobert-mumo approved these changes
LGTM @Marymary-dev

2025-01-20 13:11 UTC, merged