Filtering out invalid VLs from suppression computation
palladiumkenya/dwh-etl pull request #511
Opened 2024-10-04 09:20 UTC by Marymary-dev

2024-10-04 09:27 UTC, nobert-mumo requested changes

2024-10-04 09:27 UTC, nobert-mumo commented on Scripts/REPORTING/1_load_Linelist-FACTART.sql
> +    Case when vl.HasValidVL= 1 Then vl.ValidVLSup Else 0 End as ValidVLSup,
@Marymary-dev oh interesting, should we do the fix at the fact level? I think if the name of the column is `ValidVLSup` then the issue could be on the fact logic

2024-10-04 18:15 UTC, Marymary-dev commented on Scripts/REPORTING/1_load_Linelist-FACTART.sql
> +    Case when vl.HasValidVL= 1 Then vl.ValidVLSup Else 0 End as ValidVLSup,
@nobert-mumo  this has been fixed at the Fact level

2025-02-23 21:37 UTC, nobert-mumo commented on Scripts/NDWH/C&T FACT TABLES/load_FactViralLoad.sql
> +			case  when valid_VL_indicators.PatientPK is not null  and valid_VL_indicators.ValidVLSup is not null then valid_VL_indicators.ValidVLSup else 0 end as ValidVLSup,
@Marymary-dev it would be great to still investigate this.

2025-02-25 12:47 UTC, Marymary-dev commented on Scripts/NDWH/C&T FACT TABLES/load_FactViralLoad.sql
> +			case  when valid_VL_indicators.PatientPK is not null  and valid_VL_indicators.ValidVLSup is not null then valid_VL_indicators.ValidVLSup else 0 end as ValidVLSup,
@nobert-mumo  the issue was the pbfw who had invalid vls yet they were not filtered out from the valid vls suppression , this has been resolved

2025-02-27 08:21 UTC, nobert-mumo commented on Scripts/REPORTING/1_load_Linelist-FACTART.sql
> +    ValidVLSup,
nitpik: rem to add back the table reference :)

2025-02-27 08:22 UTC, nobert-mumo approved these changes
LGTM with the samll comment

2025-02-27 11:44 UTC, merged