Load fact tables
palladiumkenya/dwh-etl pull request #89
Opened 2023-02-06 06:55 UTC by Marymary-dev

2023-02-06 07:31 UTC, cbrianbet approved these changes

2023-02-06 19:44 UTC, nobert-mumo requested changes
Hi @Marymary-dev I think this would be a replica of FactPatientExits; should we do away with it ?

2023-02-10 14:12 UTC, Marymary-dev commented
> Hi @Marymary-dev I think this would be a replica of FactPatientExits; should we do away with it ?

Yes will delete FACT_PatientExits

2023-02-15 09:18 UTC, Marymary-dev commented
> > Hi @Marymary-dev I think this would be a replica of FactPatientExits; should we do away with it ?
> 
> Yes will delete FACT_PatientExits

@nobert-mumo  this has been done

2023-02-15 09:50 UTC, nthusi-codes approved these changes

2023-02-15 11:45 UTC, nobert-mumo approved these changes

2023-02-15 11:46 UTC, merged